version: '3.1'

services:

  pg:
    container_name: pg
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:4.22
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}
  #     PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
  #   depends_on:
  #     - pg
  #   ports:
  #     - 8080:80

  mongo:
    container_name: mongo
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
    depends_on:
      - mongo
    ports:
      - 8081:8081

